#!/bin/sh
# DEPENDS ON: NONE

bram() {
    FREE="$(free -h | grep -i mem)"
    RAM_USED="$(echo "$FREE" | awk '{ print $3 }')"
    RAM_TOTAL="$(echo "$FREE" | awk '{ print $2 }')"

    printf 'M %s/%s' "$RAM_USED" "$RAM_TOTAL"
}

