#!/bin/sh
# DEPENDS ON: $BATTERY_NAME, $BATTERY_SHOW_STATUS

bbattery() {
    CHARGE=$(cat "/sys/class/power_supply/$BATTERY_NAME/capacity")
    STATUS=$(cat "/sys/class/power_supply/$BATTERY_NAME/status")

    # TODO: ADD MORE STATUSES (NEED A LIST OF ALL STATUSES)
    if [ "$BATTERY_SHOW_STATUS" -ne 1 ]; then
        printf 'B %s%%' "$CHARGE"
    else
        if [ "$STATUS" = "Charging" ]; then
            printf "B (c) %s%%" "$CHARGE"
        else
            printf "B (d) %s%%" "$CHARGE"
        fi
    fi
}

