#!/usr/bin/env sh
# DEPENDS ON: xrandr, awk, sed

bres() {
    printf "%s" "$(xrandr --nograb --current |
        awk -F 'connected |\\+|\\(' '/ connected.*[0-9]+x[0-9]+\+/ && $2 {print $2}' |
        sed 's/primary //g')"
}
