#!/usr/bin/env sh
# DEPENDS ON: xprop, awk, cut, tr, $DEFAULT_WINDOW_TITLE

bwindow() {
    id="$(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5)"

    if [ ! "$id" ]; then
        printf '%s' "$DEFAULT_WINDOW_TITLE"
        return 0
    fi

    xprop -id "${id}" WM_NAME | awk -F '"' '{print $2}' | tr -d '\n'
}
