#!/usr/bin/env bash

die() {
    echo "FATAL ERROR: $1" >&2
    xsetroot -name "$1"

    exit 1
}

[ ! -d "$HOME" ] && die "'$HOME' is not a valid HOME directory"
. "$HOME/.config/bdwmb/config.sh" || die 'the configuration file was not found'

vecho() {
    [ "$1" ] && local p="[INFO] $1"
    echo "$p"
}

print_help() {
    echo '-q    - quiet, run without info/debug info'
    echo '-h    - print help and exit'
    echo '-l    - list modules'
}

main() {
    case "$1" in
    -q | --q | -quiet | --quiet)
        vecho() { printf ''; }
        ;;
    -h | --h | -help | --help)
        print_help
        exit
        ;;
    -l | --l | -list-modules | --list-modules)
        find "${HOME}/.config/bdwmb/modules" "/usr/share/bdwmb/modules" -type f |
            sed 's/.*\///g'
        exit
        ;;
    -*)
        die "Switch \"$1\" not found"
        ;;
    esac

    local module
    local bar_text

    for module in "${MODULES[@]}"; do
        . "$HOME/.config/bdwmb/modules/$module" 2>/dev/null ||
            . "/usr/share/bdwmb/modules/$module" 2>/dev/null ||
            die "Failed to load module $module"

        vecho "Loading: $module (b$module)"
        bar_text+="$("b$module")"
    done
    vecho

    xsetroot -name "$bar_text"
}

while true; do
    main "$@"
    [ "$DELAY" ] && sleep -- "$DELAY"
done
