#!/usr/bin/env bash

HOME="${HOME:-$(eval echo ~)}"

die() {
    echo "FATAL ERROR: $1"
    xsetroot -name "$1"

    exit 1
}

. "$HOME/.config/bdwmb/config.sh" || die 'the configuration file was not found'

vecho() {
    [[ "$1" ]] && local p="[INFO] $1"
    echo "$p"
}

print_help() {
    echo '-q    - quiet, run without info/debug info'
    echo '-h    - print help and exit'
}

main() {
    case "$1" in
    -q | --q | -quiet | --quiet)
        vecho() { printf ''; }
        ;;
    -h | --h | -help | --help)
        print_help
        exit
        ;;
    *)
        die "Switch \"$1\" not found"
        ;;
    esac

    local module
    local bar_text

    for module in "${MODULES[@]}"; do
        . "$HOME/.config/bdwmb/modules/$module" 2>/dev/null ||
            . "/usr/share/bdwmb/modules/$module" ||
            die "Failed to load module $module"

        vecho "Loading: $module (b$module)"
        bar_text+="$("b$module")"
    done
    vecho

    xsetroot -name "$bar_text"
}

while true; do
    main "$@"
    [[ "$DELAY" ]] && sleep "$DELAY"
done
